/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.DNBUS;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author MSI
 */
public class DN extends javax.swing.JFrame {

    DNBUS bus = new DNBUS();

    /**
     * Creates new form DN
     */
    public DN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnDN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtMK = new javax.swing.JPasswordField();
        register = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Đăng nhập");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tên đăng nhập");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 42, -1, -1));

        txtDN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(txtDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 73, 324, 45));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Mật khẩu");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 137, -1, -1));

        btnDN.setBackground(new java.awt.Color(51, 153, 255));
        btnDN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDN.setForeground(new java.awt.Color(255, 255, 255));
        btnDN.setText("Đăng nhập");
        btnDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNActionPerformed(evt);
            }
        });
        btnDN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDNKeyPressed(evt);
            }
        });
        jPanel2.add(btnDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 249, 324, 43));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Quên mật khẩu ?");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 310, -1, -1));

        txtMK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMKKeyPressed(evt);
            }
        });
        jPanel2.add(txtMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 173, 324, 43));

        register.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        register.setForeground(new java.awt.Color(0, 204, 255));
        register.setText("Tạo tài khoản mới");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        register.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                registerKeyPressed(evt);
            }
        });
        jPanel2.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 440, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 540, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_warehouse_200px.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 183, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 0, 400, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNActionPerformed
        String user = txtDN.getText();
        String password = txtMK.getText();
        //DangNhap DN = new DangNhap();
        if (user.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(this, "Không được để trống");
        } else {
            bus.DNhap(user, password);
        }
        dispose();
    }//GEN-LAST:event_btnDNActionPerformed

    private void btnDNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDNKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String user = txtDN.getText();
            String password = txtMK.getText();
            //DangNhap DN = new DangNhap();
            if (user.equals("") || password.equals("")) {
                JOptionPane.showMessageDialog(this, "Không được để trống");
            } else {
                bus.DNhap(user, password);
            }
            dispose();
        }
    }//GEN-LAST:event_btnDNKeyPressed

    private void registerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registerKeyPressed

    }//GEN-LAST:event_registerKeyPressed

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked

    }//GEN-LAST:event_registerMouseClicked

    private void txtMKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMKKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String user = txtDN.getText();
            String password = txtMK.getText();
            //DangNhap DN = new DangNhap();
            if (user.equals("") || password.equals("")) {
                JOptionPane.showMessageDialog(this, "Không được để trống");
            } else {
                bus.DNhap(user, password);
            }
            dispose();
        }
    }//GEN-LAST:event_txtMKKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel register;
    private javax.swing.JTextField txtDN;
    private javax.swing.JPasswordField txtMK;
    // End of variables declaration//GEN-END:variables
}
